name: network_layer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  provider:
  cupertino_icons: ^0.1.3
  fluttertoast: ^7.1.6
  flutter_flavorizr: ^1.0.9
  flutter_launcher_icons: ^0.8.1
  device_info: ^1.0.0
  package_info: ^0.4.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "Flutter Template DEV"
      android:
        applicationId: "com.flutter_project_template.app.dev"
      ios:
        bundleId: "com.flutter_project_template.app.dev"
    prod:
      app:
        name: "Flutter Template PROD"
      android:
        applicationId: "com.flutter_project_template.app"
      ios:
        bundleId: "com.flutter_project_template.app"

flutter:
  uses-material-design: true
